application: projectweek
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main1.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
